import { defineConfig } from 'astro/config';
import { readFileSync } from 'node:fs';

// Generated by scripts/build-redirects.mjs, which runs before every build.
const redirects = JSON.parse(readFileSync(new URL('./src/data/redirects.json', import.meta.url), 'utf8'));

export default defineConfig({
  site: 'https://smartpetindex.com',
  trailingSlash: 'always',
  build: { format: 'directory' },
  redirects,
});
