// Seeds the product + brand database. Run: node scripts/seed-catalog.mjs
// Specs are compiled from manufacturer documentation and retail listings.
// Scores are research-based until hands-on testing replaces them.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const productDir = join(root, 'src/data/products');
const brandDir = join(root, 'src/data/brands');
mkdirSync(productDir, { recursive: true });
mkdirSync(brandDir, { recursive: true });

const brands = [
  {
    slug: 'whisker',
    name: 'Whisker',
    aka: 'Litter-Robot',
    country: 'United States',
    founded: 1999,
    site: 'litter-robot.com',
    summary:
      'The company that invented this category and still sets the benchmark. Whisker builds the Litter-Robot line in Michigan, sells direct, and charges accordingly. Support and parts availability are the best in the market; the prices are the worst.',
    strengths: ['Best-in-class support and spare parts', 'Genuinely quiet mechanisms', 'No proprietary consumables'],
    weaknesses: ['Highest prices in the category', 'Large footprint', 'Subscription upsells at checkout'],
  },
  {
    slug: 'catlink',
    name: 'CATLINK',
    country: 'China',
    founded: 2018,
    site: 'catlink.com',
    summary:
      'CATLINK undercuts Whisker by a few hundred dollars and matches most of the hardware. The build is solid, the app is competent, and the odor systems are among the more aggressive on the market. Support is slower and firmware updates are less predictable.',
    strengths: ['Strong odor hardware for the money', 'Deep app feature set', 'Frequent hardware revisions'],
    weaknesses: ['Support response times', 'Model naming is confusing', 'Some models need proprietary bags'],
  },
  {
    slug: 'petkit',
    name: 'PETKIT',
    country: 'China',
    founded: 2013,
    site: 'petkit.com',
    summary:
      'PETKIT is the widest smart-pet range of any brand here, and the litter boxes reflect that — lots of features, heavy app integration, and a consumables business attached to almost every product.',
    strengths: ['Feature density per dollar', 'Mature app with real health tracking', 'Wide accessory ecosystem'],
    weaknesses: ['Proprietary bag rolls on most models', 'App wants an account for everything', 'Uneven translation in docs'],
  },
  {
    slug: 'neakasa',
    name: 'Neakasa',
    country: 'China',
    founded: 2019,
    site: 'neakasa.com',
    summary:
      'Neakasa came out of the vacuum world and brought that sensibility to litter boxes: open-top designs that cats accept quickly, and a focus on how easily the thing comes apart for cleaning.',
    strengths: ['Open-top design cats accept fast', 'Easy full teardown for cleaning', 'Uses standard bags'],
    weaknesses: ['Open top costs some odor containment', 'Shorter track record', 'Thinner accessory range'],
  },
  {
    slug: 'casa-leo',
    name: 'Casa Leo',
    country: 'United States',
    founded: 2020,
    site: 'casaleo.com',
    summary:
      "Casa Leo's Leo's Loo Too is the most direct challenger to the Litter-Robot at a lower price, with a comparable globe design and a much more aggressive odor package.",
    strengths: ['UV sterilisation and deodoriser included', 'Competitive against Litter-Robot on price', 'Standard bags'],
    weaknesses: ['Smaller company, thinner parts supply', 'App is functional but plain', 'Fewer safety redundancies'],
  },
  {
    slug: 'petsnowy',
    name: 'PetSnowy',
    country: 'China',
    founded: 2021,
    site: 'petsnowy.com',
    summary:
      'PetSnowy built its pitch entirely around odor: a heat-sealed waste system that closes the bag after every cycle. It works, and it locks you into their film cartridges forever.',
    strengths: ['Best-sealed waste system in the category', 'Distinctive design', 'Quiet operation'],
    weaknesses: ['Proprietary sealing film is mandatory', 'Highest consumable cost here', 'Small support footprint'],
  },
  {
    slug: 'petsafe',
    name: 'PetSafe',
    country: 'United States',
    founded: 1991,
    site: 'petsafe.com',
    summary:
      'PetSafe is the mass-retail incumbent. ScoopFree predates most of this category and uses a rake-and-tray design rather than a rotating globe. Cheap to buy, expensive to feed.',
    strengths: ['Widely stocked and easy to return', 'Low entry price', 'Simple mechanism, little to break'],
    weaknesses: ['Crystal tray refills are costly and mandatory', 'No clumping litter support', 'Basic app'],
  },
  {
    slug: 'meowant',
    name: 'Meowant',
    country: 'China',
    founded: 2022,
    site: 'meowant.com',
    summary:
      'Meowant is the value entry in the rotating-globe format — most of the mechanism of a $500 box for around $300, with the corners cut in materials and app polish rather than in safety.',
    strengths: ['Rotating-globe design at a budget price', 'Standard bags', 'Reasonable safety sensor coverage'],
    weaknesses: ['Plastics feel cheaper', 'App is basic', 'Very short market history'],
  },
  {
    slug: 'omega-paw',
    name: 'Omega Paw',
    country: 'Canada',
    founded: 1998,
    site: 'omegapaw.com',
    summary:
      'Not automatic and not smart — you roll it by hand. It is in this index because it solves the same problem for under $50, with no motor, no app and no consumables.',
    strengths: ['Costs less than a month of some refill plans', 'Nothing to break', 'No power required'],
    weaknesses: ['Entirely manual', 'No odor system beyond the hood', 'No data, no alerts'],
  },
];

const products = [
  {
    slug: 'litter-robot-4',
    brand: 'whisker',
    model: 'Litter-Robot 4',
    shortName: 'Litter-Robot 4',
    category: 'litter-boxes',
    price: 699,
    releaseYear: 2022,
    accent: '#3b6ea5',
    specs: {
      dimensions: '22 x 27 x 29.5 in',
      footprint: '22 x 27 in',
      entryHeight: '8.5 in',
      weight: '24 lb',
      minimumCatWeight: '3 lb',
      maximumCatWeight: '20 lb',
      wasteCapacity: '9.2 L',
      litterTypes: ['Clumping clay'],
      wifi: true,
      app: 'Whisker (iOS, Android)',
      odorSystem: 'OdorTrap pods + carbon filter + sealed drawer',
      noiseLevel: '~44 dB at 3 ft',
      safetySensors: ['SafeCat weight sensor', 'Laser entry detection', 'Pinch detect', 'Anti-pinch bonnet'],
      bagType: 'Standard kitchen bags',
      replacementCost: 30,
      filterCost: 60,
      warranty: '1 year (3 with WhiskerCare)',
      multiCatCapable: true,
      catsSupported: 'Up to 4',
      cycleTime: '~2 min 30 s',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 9.1, odorControl: 8.9, safety: 9.5, app: 9.0, maintenance: 8.7, value: 7.0 },
    verdict:
      'The Litter-Robot 4 is the box to beat and it knows it. Cleaning is close to flawless, the safety sensor stack is the most redundant in the category, and it runs quietly enough to sit in a bedroom. It is also the most expensive box here by a wide margin, and the value case only works if you keep it for years — which, given how well Whisker supports these, is a realistic assumption.',
    pros: [
      'Most reliable cleaning cycle we have found data on',
      'Four independent safety systems, including laser entry detection',
      'Uses ordinary kitchen bags — no consumable lock-in',
      'Quietest full-size globe design',
      'Excellent parts availability and support',
    ],
    cons: ['Costs $200-$400 more than comparable boxes', 'Large footprint for small bathrooms', 'Carbon filters are a recurring cost'],
    bestFor: ['Multi-cat homes', 'People who want it to just work', 'Bedrooms and small apartments where noise matters'],
    notIdealFor: ['Tight budgets', 'Very large cats over 20 lb', 'Homes with no space for a 22 x 27 in footprint'],
  },
  {
    slug: 'litter-robot-3-connect',
    brand: 'whisker',
    model: 'Litter-Robot 3 Connect',
    shortName: 'Litter-Robot 3',
    category: 'litter-boxes',
    price: 549,
    releaseYear: 2015,
    accent: '#5b7f9e',
    specs: {
      dimensions: '24.25 x 27 x 29.5 in',
      footprint: '24.25 x 27 in',
      entryHeight: '10 in',
      weight: '24 lb',
      minimumCatWeight: '5 lb',
      maximumCatWeight: '15 lb',
      wasteCapacity: '7.5 L',
      litterTypes: ['Clumping clay'],
      wifi: true,
      app: 'Whisker (iOS, Android)',
      odorSystem: 'Carbon filter + sealed drawer',
      noiseLevel: '~50 dB at 3 ft',
      safetySensors: ['Weight sensor', 'Cat sensor pause'],
      bagType: 'Standard kitchen bags',
      replacementCost: 30,
      filterCost: 45,
      warranty: '18 months',
      multiCatCapable: true,
      catsSupported: 'Up to 4',
      cycleTime: '~2 min 45 s',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.6, odorControl: 8.0, safety: 8.4, app: 8.2, maintenance: 8.0, value: 7.6 },
    verdict:
      'The older Litter-Robot is still on sale because it still works. The mechanism is proven over a decade, parts are everywhere, and it regularly discounts below $500. You give up the newer laser sensor, the higher weight limit and a noticeable amount of quiet, but for a single average-sized cat the practical difference is smaller than the price gap suggests.',
    pros: [
      'A decade of proven reliability and parts supply',
      'Frequently discounted well below the LR4',
      'No proprietary consumables',
      'Simple to repair — most parts are user-replaceable',
    ],
    cons: ['Noticeably louder than the LR4', '15 lb cat weight ceiling', '10 in entry is high for kittens and seniors'],
    bestFor: ['Single-cat homes', 'Buyers who want Whisker support at a lower price', 'People who like repairable hardware'],
    notIdealFor: ['Large cats', 'Kittens or arthritic seniors', 'Anyone sensitive to motor noise'],
  },
  {
    slug: 'catlink-scooper-pro-x',
    brand: 'catlink',
    model: 'CATLINK Scooper Pro X',
    shortName: 'CATLINK Pro X',
    category: 'litter-boxes',
    price: 499,
    releaseYear: 2023,
    accent: '#6b8f7a',
    specs: {
      dimensions: '21.6 x 25.6 x 25.6 in',
      footprint: '21.6 x 25.6 in',
      entryHeight: '7.9 in',
      weight: '27 lb',
      minimumCatWeight: '3.3 lb',
      maximumCatWeight: '22 lb',
      wasteCapacity: '11 L',
      litterTypes: ['Clumping clay', 'Tofu', 'Mixed'],
      wifi: true,
      app: 'CATLINK (iOS, Android)',
      odorSystem: 'Ozone-free deodoriser + carbon filter + sealed drawer',
      noiseLevel: '~48 dB at 3 ft',
      safetySensors: ['Infrared entry', 'Weight sensor', 'Anti-pinch reverse'],
      bagType: 'Standard kitchen bags',
      replacementCost: 30,
      filterCost: 50,
      warranty: '1 year',
      multiCatCapable: true,
      catsSupported: 'Up to 4',
      cycleTime: '~3 min',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.7, odorControl: 8.8, safety: 8.5, app: 8.3, maintenance: 8.2, value: 8.6 },
    verdict:
      'The Pro X is the strongest all-round argument against paying Litter-Robot money. The drawer is bigger, the litter compatibility is wider, the entry is lower, and it takes ordinary bags. What you trade away is Whisker-grade support and the sense that firmware will still be updated in three years. For most multi-cat homes that is a trade worth making.',
    pros: [
      'Largest waste drawer in this price bracket',
      'Accepts tofu and mixed litter, not just clay',
      '7.9 in entry suits kittens and older cats',
      'Standard kitchen bags',
      'Roughly $200 less than the LR4',
    ],
    cons: ['Support is slower than Whisker', 'Louder cycle', 'Firmware update cadence is unpredictable'],
    bestFor: ['Multi-cat homes', 'Tofu litter users', 'Value-focused buyers who still want a full-size globe'],
    notIdealFor: ['Buyers who want US-based phone support', 'Very noise-sensitive rooms'],
  },
  {
    slug: 'catlink-luxury-pro',
    brand: 'catlink',
    model: 'CATLINK Luxury Pro',
    shortName: 'CATLINK Luxury Pro',
    category: 'litter-boxes',
    price: 429,
    releaseYear: 2022,
    accent: '#7d9a86',
    specs: {
      dimensions: '21.6 x 24.4 x 25.2 in',
      footprint: '21.6 x 24.4 in',
      entryHeight: '8.3 in',
      weight: '25 lb',
      minimumCatWeight: '3.3 lb',
      maximumCatWeight: '18 lb',
      wasteCapacity: '9 L',
      litterTypes: ['Clumping clay', 'Tofu'],
      wifi: true,
      app: 'CATLINK (iOS, Android)',
      odorSystem: 'Carbon filter + sealed drawer',
      noiseLevel: '~50 dB at 3 ft',
      safetySensors: ['Infrared entry', 'Weight sensor'],
      bagType: 'Standard kitchen bags',
      replacementCost: 30,
      filterCost: 45,
      warranty: '1 year',
      multiCatCapable: true,
      catsSupported: 'Up to 3',
      cycleTime: '~3 min',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.3, odorControl: 8.0, safety: 8.0, app: 8.1, maintenance: 7.9, value: 8.8 },
    verdict:
      'The Luxury Pro is the previous-generation Scooper with a smaller drawer and one fewer safety layer, and it sells for around $70 less. It is a sensible pick for a one- or two-cat household that wants a full-size globe box without paying premium prices, and it is often the cheapest way into a genuinely capable smart box.',
    pros: [
      'Full-size globe mechanism under $450',
      'Accepts tofu litter',
      'Standard kitchen bags',
      'Same app as the more expensive CATLINK models',
    ],
    cons: ['Only two safety systems', 'Smaller drawer than the Pro X', 'Noisier than the premium tier'],
    bestFor: ['One or two cats', 'First-time automatic box buyers', 'Budget-conscious tofu litter users'],
    notIdealFor: ['Three or more cats', 'Cats over 18 lb'],
  },
  {
    slug: 'petkit-purobot-ultra',
    brand: 'petkit',
    model: 'PETKIT Purobot Ultra',
    shortName: 'Purobot Ultra',
    category: 'litter-boxes',
    price: 899,
    releaseYear: 2024,
    accent: '#4f7fa8',
    specs: {
      dimensions: '22.4 x 25.2 x 24.8 in',
      footprint: '22.4 x 25.2 in',
      entryHeight: '8.7 in',
      weight: '30 lb',
      minimumCatWeight: '3.3 lb',
      maximumCatWeight: '17.6 lb',
      wasteCapacity: '10 L',
      litterTypes: ['Clumping clay', 'Tofu', 'Mixed'],
      wifi: true,
      app: 'PETKIT (iOS, Android)',
      odorSystem: 'Dual deodoriser + carbon filter + sealed bag roll',
      noiseLevel: '~46 dB at 3 ft',
      safetySensors: ['AI camera', 'Infrared', 'Weight sensor', 'Anti-pinch reverse'],
      bagType: 'Proprietary bag roll',
      replacementCost: 90,
      filterCost: 55,
      warranty: '1 year',
      multiCatCapable: true,
      catsSupported: 'Up to 4',
      cycleTime: '~2 min 40 s',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.8, odorControl: 9.0, safety: 8.9, app: 9.2, maintenance: 7.4, value: 6.4 },
    verdict:
      'The Purobot Ultra is the most technically ambitious box on the market — an AI camera that identifies which cat is using it, health tracking that is genuinely useful in a multi-cat home, and the best app in the category by some distance. It is also $899 and locked to PETKIT bag rolls, which is roughly $90 a year you cannot opt out of. Buy it for the health data, not for the scooping.',
    pros: [
      'Camera identifies individual cats without collars',
      'Best app in the category — the health data is actually actionable',
      'Very strong odor performance',
      'Broad litter compatibility',
    ],
    cons: [
      'Most expensive box in this index',
      'Proprietary bag rolls at roughly $90 a year',
      'Camera means a privacy decision most boxes do not ask you to make',
      'Fiddly to fully disassemble for deep cleaning',
    ],
    bestFor: ['Multi-cat homes needing per-cat health data', 'Cats with a monitored medical condition', 'App-first buyers'],
    notIdealFor: ['Anyone avoiding consumable lock-in', 'Privacy-sensitive households', 'Budget buyers'],
  },
  {
    slug: 'petkit-pura-max-2',
    brand: 'petkit',
    model: 'PETKIT Pura Max 2',
    shortName: 'Pura Max 2',
    category: 'litter-boxes',
    price: 429,
    releaseYear: 2024,
    accent: '#6892b5',
    specs: {
      dimensions: '21.7 x 25.2 x 24.4 in',
      footprint: '21.7 x 25.2 in',
      entryHeight: '8.7 in',
      weight: '26 lb',
      minimumCatWeight: '3.3 lb',
      maximumCatWeight: '17.6 lb',
      wasteCapacity: '9 L',
      litterTypes: ['Clumping clay', 'Tofu', 'Mixed'],
      wifi: true,
      app: 'PETKIT (iOS, Android)',
      odorSystem: 'Deodoriser module + carbon filter + sealed bag roll',
      noiseLevel: '~48 dB at 3 ft',
      safetySensors: ['Infrared', 'Weight sensor', 'Anti-pinch reverse'],
      bagType: 'Proprietary bag roll',
      replacementCost: 90,
      filterCost: 50,
      warranty: '1 year',
      multiCatCapable: true,
      catsSupported: 'Up to 3',
      cycleTime: '~2 min 45 s',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.4, odorControl: 8.6, safety: 8.2, app: 9.0, maintenance: 7.5, value: 7.8 },
    verdict:
      'The Pura Max 2 is the Purobot with the camera removed and $470 knocked off, and for most households that is the smarter purchase. You keep the excellent app, the strong deodoriser and the wide litter compatibility. You still pay for PETKIT bag rolls, which over three years quietly erases the price advantage over boxes that take kitchen bags.',
    pros: [
      'Same excellent PETKIT app at half the Purobot price',
      'Strong active deodoriser',
      'Accepts tofu and mixed litter',
      'Compact for a full-capacity box',
    ],
    cons: ['Proprietary bag rolls at roughly $90 a year', 'No camera or per-cat identification', '17.6 lb weight ceiling'],
    bestFor: ['App-focused buyers on a mid budget', 'Two-cat homes', 'Tofu litter users'],
    notIdealFor: ['Large cats', 'Anyone who refuses consumable subscriptions'],
  },
  {
    slug: 'neakasa-m1',
    brand: 'neakasa',
    model: 'Neakasa M1',
    shortName: 'Neakasa M1',
    category: 'litter-boxes',
    price: 599,
    releaseYear: 2023,
    accent: '#7fa38c',
    specs: {
      dimensions: '23.6 x 20.5 x 20.9 in',
      footprint: '23.6 x 20.5 in',
      entryHeight: '5.9 in',
      weight: '22 lb',
      minimumCatWeight: '2.2 lb',
      maximumCatWeight: '22 lb',
      wasteCapacity: '8 L',
      litterTypes: ['Clumping clay', 'Tofu', 'Mixed', 'Crystal'],
      wifi: true,
      app: 'Neakasa (iOS, Android)',
      odorSystem: 'Sealed drawer + carbon filter (open top)',
      noiseLevel: '~42 dB at 3 ft',
      safetySensors: ['Infrared entry', 'Weight sensor', 'Anti-pinch reverse'],
      bagType: 'Standard kitchen bags',
      replacementCost: 30,
      filterCost: 40,
      warranty: '2 years',
      multiCatCapable: true,
      catsSupported: 'Up to 4',
      cycleTime: '~2 min',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.5, odorControl: 7.6, safety: 9.0, app: 7.9, maintenance: 9.1, value: 8.4 },
    verdict:
      'The M1 solves the single biggest failure mode of automatic litter boxes: cats that refuse to enter an enclosed globe. The open top means most cats accept it in days rather than weeks, the 5.9 in entry is the lowest here, and it comes apart for cleaning faster than anything else in this index. The cost is odor — an open box cannot contain smell between cycles the way a sealed globe can.',
    pros: [
      'Open top — the highest cat acceptance rate of any design here',
      'Lowest entry height in this index at 5.9 in',
      'Easiest full teardown for deep cleaning',
      'Two-year warranty',
      'Accepts almost any litter, including crystal',
    ],
    cons: ['Open design limits odor containment between cycles', 'App is the plainest of the smart boxes', 'Wide footprint'],
    bestFor: ['Cats that refuse enclosed boxes', 'Kittens and senior cats', 'People who deep-clean often'],
    notIdealFor: ['Rooms where odor containment is the top priority', 'Homes wanting a small footprint'],
  },
  {
    slug: 'casa-leo-leos-loo-too',
    brand: 'casa-leo',
    model: "Casa Leo Leo's Loo Too",
    shortName: "Leo's Loo Too",
    category: 'litter-boxes',
    price: 649,
    releaseYear: 2022,
    accent: '#5f88a8',
    specs: {
      dimensions: '22 x 23.6 x 24.4 in',
      footprint: '22 x 23.6 in',
      entryHeight: '8.3 in',
      weight: '26 lb',
      minimumCatWeight: '3 lb',
      maximumCatWeight: '20 lb',
      wasteCapacity: '9 L',
      litterTypes: ['Clumping clay', 'Tofu'],
      wifi: true,
      app: "Leo's Loo (iOS, Android)",
      odorSystem: 'UV sterilisation + active deodoriser + carbon filter',
      noiseLevel: '~47 dB at 3 ft',
      safetySensors: ['Infrared', 'Weight sensor', 'Anti-pinch reverse'],
      bagType: 'Standard kitchen bags',
      replacementCost: 30,
      filterCost: 50,
      warranty: '1 year',
      multiCatCapable: true,
      catsSupported: 'Up to 3',
      cycleTime: '~2 min 30 s',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.4, odorControl: 9.1, safety: 8.6, app: 7.8, maintenance: 8.3, value: 8.0 },
    verdict:
      "Leo's Loo Too throws more hardware at odor than anything else that still takes ordinary bags — UV sterilisation, an active deodoriser and carbon filtration in one drawer. If smell is the problem you are actually trying to solve and you do not want to be locked into film cartridges, this is the most direct answer. The app is the weak link and feels a generation behind.",
    pros: [
      'The most complete odor package that still uses standard bags',
      'UV sterilisation is genuinely unusual at this price',
      'Compact footprint for a globe box',
      'Handles cats up to 20 lb',
    ],
    cons: ['App is basic compared with PETKIT or Whisker', 'Smaller company means thinner parts supply', 'Only two litter types supported'],
    bestFor: ['Small apartments where odor is the whole problem', 'Buyers avoiding proprietary consumables', 'Multi-cat homes up to three cats'],
    notIdealFor: ['App-first buyers', 'People who want long-term parts certainty'],
  },
  {
    slug: 'petsnowy-snow-plus',
    brand: 'petsnowy',
    model: 'PetSnowy SNOW+',
    shortName: 'PetSnowy SNOW+',
    category: 'litter-boxes',
    price: 649,
    releaseYear: 2023,
    accent: '#8aa9c4',
    specs: {
      dimensions: '23.6 x 21.7 x 24.8 in',
      footprint: '23.6 x 21.7 in',
      entryHeight: '7.5 in',
      weight: '28 lb',
      minimumCatWeight: '2.2 lb',
      maximumCatWeight: '19.8 lb',
      wasteCapacity: '7 L (heat-sealed)',
      litterTypes: ['Clumping clay', 'Tofu', 'Mixed'],
      wifi: true,
      app: 'PetSnowy (iOS, Android)',
      odorSystem: 'Heat-sealed waste bag + deodoriser + carbon filter',
      noiseLevel: '~45 dB at 3 ft',
      safetySensors: ['Infrared', 'Weight sensor', 'Anti-pinch reverse'],
      bagType: 'Proprietary sealing film cartridge',
      replacementCost: 120,
      filterCost: 45,
      warranty: '1 year',
      multiCatCapable: true,
      catsSupported: 'Up to 3',
      cycleTime: '~2 min 20 s',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 8.5, odorControl: 9.4, safety: 8.4, app: 8.0, maintenance: 8.0, value: 6.8 },
    verdict:
      'The SNOW+ heat-seals the waste bag after every cycle, and on the evidence available it is the most effective odor solution in this category — nothing else physically closes the bag. The catch is unavoidable: the sealing film is proprietary, it costs roughly $120 a year, and if PetSnowy stops making it the box becomes an ordinary one. That is the whole trade.',
    pros: [
      'Heat-sealed bags — the strongest odor containment available',
      'Very quiet',
      'Low 7.5 in entry',
      'Handles tofu and mixed litter',
    ],
    cons: [
      'Sealing film is proprietary and mandatory at around $120 a year',
      'Smaller effective waste capacity because of the sealing mechanism',
      'Long-term dependence on one supplier',
    ],
    bestFor: ['Studio apartments', 'Households where odor is a dealbreaker', 'People who do not mind consumables'],
    notIdealFor: ['Anyone avoiding proprietary refills', 'Cost-per-year optimisers'],
  },
  {
    slug: 'petsafe-scoopfree-smart',
    brand: 'petsafe',
    model: 'PetSafe ScoopFree Smart',
    shortName: 'ScoopFree Smart',
    category: 'litter-boxes',
    price: 229,
    releaseYear: 2022,
    accent: '#8f9bab',
    specs: {
      dimensions: '27.4 x 19.1 x 6.9 in',
      footprint: '27.4 x 19.1 in',
      entryHeight: '5.5 in',
      weight: '12 lb',
      minimumCatWeight: 'No minimum',
      maximumCatWeight: '15 lb',
      wasteCapacity: '1 disposable tray',
      litterTypes: ['Crystal (proprietary trays)'],
      wifi: true,
      app: 'PetSafe (iOS, Android)',
      odorSystem: 'Crystal litter absorption + covered tray',
      noiseLevel: '~40 dB at 3 ft',
      safetySensors: ['Infrared entry', 'Rake obstruction reverse'],
      bagType: 'Proprietary disposable crystal tray',
      replacementCost: 220,
      filterCost: 0,
      warranty: '1 year',
      multiCatCapable: false,
      catsSupported: '1',
      cycleTime: '~30 s rake',
      power: 'Mains adapter',
    },
    scores: { cleaning: 7.2, odorControl: 7.4, safety: 7.6, app: 6.9, maintenance: 7.8, value: 6.6 },
    verdict:
      'The ScoopFree is the cheapest way to stop scooping, and the most expensive way to own a litter box. The rake mechanism is simple and hard to break, the low profile fits where a globe never will, and the app is adequate. But the disposable crystal trays run roughly $220 a year, which means it costs more than a Litter-Robot over four years while doing less.',
    pros: [
      'Lowest purchase price of any powered box here',
      'Very low 5.5 in entry and flat profile',
      'Simple rake mechanism with little to fail',
      'Sold in mainstream retail with easy returns',
    ],
    cons: [
      'Proprietary crystal trays at roughly $220 a year',
      'No clumping litter support at all',
      'Single-cat only in practice',
      'Costs more than a premium box over four years',
    ],
    bestFor: ['One small cat', 'Low-ceiling or narrow spaces', 'Buyers who want the lowest sticker price'],
    notIdealFor: ['Multi-cat homes', 'Anyone calculating cost per year', 'Clumping litter users'],
  },
  {
    slug: 'meowant-sc-m01',
    brand: 'meowant',
    model: 'Meowant SC-M01',
    shortName: 'Meowant SC-M01',
    category: 'litter-boxes',
    price: 299,
    releaseYear: 2023,
    accent: '#93a88f',
    specs: {
      dimensions: '21.3 x 23.6 x 24.0 in',
      footprint: '21.3 x 23.6 in',
      entryHeight: '8.3 in',
      weight: '23 lb',
      minimumCatWeight: '3.3 lb',
      maximumCatWeight: '16.5 lb',
      wasteCapacity: '8 L',
      litterTypes: ['Clumping clay', 'Tofu'],
      wifi: true,
      app: 'Meowant (iOS, Android)',
      odorSystem: 'Carbon filter + sealed drawer',
      noiseLevel: '~52 dB at 3 ft',
      safetySensors: ['Infrared entry', 'Weight sensor', 'Anti-pinch reverse'],
      bagType: 'Standard kitchen bags',
      replacementCost: 30,
      filterCost: 35,
      warranty: '1 year',
      multiCatCapable: true,
      catsSupported: 'Up to 2',
      cycleTime: '~3 min 10 s',
      power: 'Mains, 24 V adapter',
    },
    scores: { cleaning: 7.9, odorControl: 7.5, safety: 8.0, app: 7.0, maintenance: 7.6, value: 9.1 },
    verdict:
      'The SC-M01 is the cheapest rotating-globe box worth taking seriously. It has the three safety systems that matter, it takes ordinary kitchen bags, and it costs a third of a Litter-Robot. The plastics feel it, the motor is the loudest here, and the app does the minimum. For a first automatic box in a one- or two-cat home, that is a defensible set of compromises.',
    pros: [
      'Full globe mechanism for under $300',
      'Standard kitchen bags — no consumable lock-in',
      'Three safety systems despite the price',
      'Lowest running cost of any powered box here',
    ],
    cons: ['Loudest cycle in this index', 'Materials feel budget', 'App is bare-bones', 'Short company track record'],
    bestFor: ['First-time buyers', 'One or two average-sized cats', 'The lowest possible cost per year'],
    notIdealFor: ['Noise-sensitive rooms', 'Large cats', 'Buyers who want a mature app'],
  },
  {
    slug: 'omega-paw-roll-n-clean',
    brand: 'omega-paw',
    model: "Omega Paw Roll'n Clean",
    shortName: "Omega Paw Roll'n Clean",
    category: 'litter-boxes',
    price: 45,
    releaseYear: 2004,
    accent: '#a2a297',
    specs: {
      dimensions: '21.5 x 19.5 x 20.5 in',
      footprint: '21.5 x 19.5 in',
      entryHeight: '7.0 in',
      weight: '6 lb',
      minimumCatWeight: 'No minimum',
      maximumCatWeight: '18 lb',
      wasteCapacity: 'Pull-out tray',
      litterTypes: ['Clumping clay'],
      wifi: false,
      app: 'None',
      odorSystem: 'Hood only',
      noiseLevel: 'Silent',
      safetySensors: ['None — manual operation'],
      bagType: 'None required',
      replacementCost: 0,
      filterCost: 0,
      warranty: '1 year',
      multiCatCapable: false,
      catsSupported: '1',
      cycleTime: 'Manual, ~10 s',
      power: 'None',
    },
    scores: { cleaning: 6.8, odorControl: 6.2, safety: 9.6, app: 0, maintenance: 8.4, value: 9.4 },
    verdict:
      'This is in the index as a reality check. You roll it on its side, the clumps fall into a tray, you pull the tray. It costs $45, uses no power, has nothing to break and no consumables. It is not automatic and it has no odor system beyond a hood — but for a single cat on a tight budget, it removes the daily scooping for about the price of two months of ScoopFree trays.',
    pros: [
      'Around $45 with zero running costs',
      'No motor, no firmware, nothing to fail',
      'Nothing can pinch or trap a cat',
      'Works in a power cut',
    ],
    cons: ['Entirely manual — you still handle it daily', 'No odor control beyond the hood', 'No app, alerts or weight data', 'Single cat only'],
    bestFor: ['Tight budgets', 'One cat', 'People who distrust motorised boxes'],
    notIdealFor: ['Anyone wanting hands-off operation', 'Multi-cat homes', 'Odor-sensitive rooms'],
  },
];

const RESEARCH_NOTE =
  'Scores are research-based: compiled from manufacturer specifications, retail listings, teardown coverage and a structured read of long-run owner reports. They will be replaced with hands-on measurements when this unit enters the test queue.';

for (const p of products) {
  const record = {
    ...p,
    scoreBasis: 'research',
    testedDate: null,
    scoreNote: RESEARCH_NOTE,
    lastUpdated: '2026-09-02',
    retailers: [
      { name: 'Amazon', query: p.model },
      { name: 'Chewy', query: p.model },
    ],
  };
  writeFileSync(join(productDir, p.slug + '.json'), JSON.stringify(record, null, 2) + '\n');
}

for (const b of brands) {
  writeFileSync(join(brandDir, b.slug + '.json'), JSON.stringify(b, null, 2) + '\n');
}

console.log('Seeded ' + products.length + ' products and ' + brands.length + ' brands.');
